// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hubsjxfdxhfmtwtysemu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1YnNqeGZkeGhmbXR3dHlzZW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NjU2MDYsImV4cCI6MjA3MTM0MTYwNn0.iz_UEW_3FkkTXqulDizxgiZZh0A87f9ZkivFZeOEdHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});